"""Constants shared across API services."""

VALID_LEAGUES = ["E0", "SP1", "I1", "D1", "F1"]

COMPETITIONS = {
    "E0": {"id": 2021, "name": "Premier League", "crest": "https://crests.football-data.org/PL.png"},
    "SP1": {"id": 2014, "name": "La Liga", "crest": "https://crests.football-data.org/PD.png"},
    "I1": {"id": 2019, "name": "Serie A", "crest": "https://crests.football-data.org/SA.png"},
    "D1": {"id": 2002, "name": "Bundesliga", "crest": "https://crests.football-data.org/BL1.png"},
    "F1": {"id": 2015, "name": "Ligue 1", "crest": "https://crests.football-data.org/FL1.png"},
}

TEAM_NAME_MAPPING = {
    "Arsenal FC": "Arsenal",
    "Brighton & Hove Albion FC": "Brighton",
    "Brentford FC": "Brentford",
    "Southampton FC": "Southampton",
    "Everton FC": "Everton",
    "AFC Bournemouth": "Bournemouth",
    "Ipswich Town FC": "Ipswich",
    "Fulham FC": "Fulham",
    "Leicester City FC": "Leicester",
    "Aston Villa FC": "Aston Villa",
    "Nottingham Forest FC": "Nott'm Forest",
    "Wolverhampton Wanderers FC": "Wolves",
    "West Ham United FC": "West Ham",
    "Manchester City FC": "Man City",
    "Chelsea FC": "Chelsea",
    "Crystal Palace FC": "Crystal Palace",
    "Newcastle United FC": "Newcastle",
    "Tottenham Hotspur FC": "Tottenham",
    "Manchester United FC": "Man United",
    "Liverpool FC": "Liverpool",
    "Villarreal CF": "Villarreal",
    "RC Celta de Vigo": "Celta",
    "RCD Mallorca": "Mallorca",
    "Sevilla FC": "Sevilla",
    "Rayo Vallecano de Madrid": "Vallecano",
    "FC Barcelona": "Barcelona",
    "Real Betis Balompie": "Betis",
    "Getafe CF": "Getafe",
    "Athletic Club": "Ath Bilbao",
    "Valencia CF": "Valencia",
    "Real Valladolid CF": "Valladolid",
    "CD Leganes": "Leganes",
    "Real Sociedad de Futbol": "Sociedad",
    "Deportivo Alaves": "Alaves",
    "Club Atletico de Madrid": "Ath Madrid",
    "RCD Espanyol de Barcelona": "Espanol",
    "Girona FC": "Girona",
    "CA Osasuna": "Osasuna",
    "UD Las Palmas": "Las Palmas",
    "Real Madrid CF": "Real Madrid",
    "Venezia FC": "Venezia",
    "Torino FC": "Torino",
    "FC Internazionale Milano": "Inter",
    "Atalanta BC": "Atalanta",
    "Bologna FC 1909": "Bologna",
    "Empoli FC": "Empoli",
    "US Lecce": "Lecce",
    "Cagliari Calcio": "Cagliari",
    "SS Lazio": "Lazio",
    "AC Milan": "Milan",
    "SSC Napoli": "Napoli",
    "Parma Calcio 1913": "Parma",
    "ACF Fiorentina": "Fiorentina",
    "AC Monza": "Monza",
    "Genoa CFC": "Genoa",
    "Hellas Verona FC": "Verona",
    "Juventus FC": "Juventus",
    "AS Roma": "Roma",
    "Udinese Calcio": "Udinese",
    "Como 1907": "Como",
    "1. FC Union Berlin": "Union Berlin",
    "FC St. Pauli 1910": "St Pauli",
    "VfB Stuttgart": "Stuttgart",
    "1. FSV Mainz 05": "Mainz",
    "Eintracht Frankfurt": "Ein Frankfurt",
    "TSG 1899 Hoffenheim": "Hoffenheim",
    "SV Werder Bremen": "Werder Bremen",
    "Borussia Dortmund": "Dortmund",
    "VfL Bochum 1848": "Bochum",
    "Borussia Monchengladbach": "M'gladbach",
    "Holstein Kiel": "Holstein Kiel",
    "VfL Wolfsburg": "Wolfsburg",
    "Bayer 04 Leverkusen": "Leverkusen",
    "RB Leipzig": "RB Leipzig",
    "1. FC Heidenheim 1846": "Heidenheim",
    "FC Augsburg": "Augsburg",
    "FC Bayern Munchen": "Bayern Munich",
    "SC Freiburg": "Freiburg",
    "Olympique Lyonnais": "Lyon",
    "RC Strasbourg Alsace": "Strasbourg",
    "Stade Brestois 29": "Brest",
    "AS Saint-Etienne": "St Etienne",
    "Montpellier HSC": "Montpellier",
    "FC Nantes": "Nantes",
    "Toulouse FC": "Toulouse",
    "Olympique de Marseille": "Marseille",
    "AS Monaco FC": "Monaco",
    "Angers SCO": "Angers",
    "OGC Nice": "Nice",
    "Le Havre AC": "Le Havre",
    "AJ Auxerre": "Auxerre",
    "Stade de Reims": "Reims",
    "Stade Rennais FC 1901": "Rennes",
    "Lille OSC": "Lille",
    "Paris Saint-Germain FC": "Paris SG",
    "Racing Club de Lens": "Lens",
    "AC Ajaccio": "Ajaccio",
    "FC Metz": "Metz",
}
